<a href="https://colab.research.google.com/github/mvuddandi/DeepLearning/blob/main/Getting_Started_with_PyTorch_Exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Problem Statement: **Welcome to AI Town!**

### You’ve been hired as an AI engineer in **AI Town**, a futuristic city powered by artificial intelligence. Your job is to use PyTorch to solve foundational challenges that AI Town faces. Each task requires you to demonstrate your expertise with PyTorch basics.



---



Imports and CUDA

In [1]:
import torch

# Check if CUDA (GPU) is available
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Using device: {device}")


Using device: cuda




---



**Task1: Inventory Management**

AI Town’s warehouse uses sensors to record the inventory of 5 items every day. Each day’s data is represented as a list of integers (number of units).

In [2]:
#1 Create a PyTorch Tensor from the following inventory data
inventory = [[12, 15, 10, 0, 5],
             [10, 8, 7, 5, 4],
             [20, 10, 15, 5, 2]]


In [3]:
#2 Find the total inventory for each item across all days
inv_tensor = torch.tensor(inventory)

sum = torch.sum(inv_tensor, dim=0)

sum

tensor([42, 33, 32, 10, 11])

In [4]:
#3 Find the average inventory per day
avg = torch.mean(inv_tensor.float(),dim=0)
avg

tensor([14.0000, 11.0000, 10.6667,  3.3333,  3.6667])



---



**Task2: Monitoring Vehicle Flow**

AI Town uses a sensor to monitor the number of vehicles passing through two main roads every hour. The data for one day (24 hours) is represented as two
1×24 tensors.

In [5]:
#1 Simulate this data using PyTorch's Random Functions

R1 = torch.randint(low=10, high=140, size=(24,))

R2 = torch.randint(low=20, high=240, size=(24,))

R1 , R2

(tensor([ 55, 107, 101, 119,  18, 124,  34,  56, 108,  55,  70,  87,  31, 121,
          31,  42,  73,  15,  24,  18,  37,  53, 108,  99]),
 tensor([180, 137,  77, 135,  20,  46, 148, 183,  93, 153,  30,  51,  77, 205,
          50,  48, 196, 189,  38, 112, 179,  32,  52,  78]))

In [6]:
from math import degrees
#2 Write the function to calculate the total vehicle flow for each road across the entire day

import torch

# Simulate random data for 2 roads (24 hourly readings each)
torch.manual_seed(0)
R1 = torch.randint(low=10, high=140, size=(24,))
R2 = torch.randint(low=20, high=240, size=(24,))

print("Road 1 data:\n", R1)
print("\nRoad 2 data:\n", R2)

# 2️⃣ Define a function to calculate total vehicle flow per road and overall total
def total_vehicle_flow(R1, R2):
    # Step 1: Combine both roads’ hourly traffic
    Total_Vehicle_Flow = R1 + R2

    # Step 2: Calculate total for each road individually
    total_R1 = torch.sum(R1)
    total_R2 = torch.sum(R2)

    # Step 3: Calculate total across both roads for the entire day
    total_all = torch.sum(Total_Vehicle_Flow)

    return Total_Vehicle_Flow, total_R1, total_R2, total_all


# Call the function
Total_Vehicle_Flow, total_R1, total_R2, total_all = total_vehicle_flow(R1, R2)

# Display results
print("\nTotal hourly vehicle flow across both roads:\n", Total_Vehicle_Flow)
print("\nTotal vehicles on Road 1 in a day:", total_R1.item())
print("Total vehicles on Road 2 in a day:", total_R2.item())
print("Overall total vehicle flow (both roads combined):", total_all.item())


Road 1 data:
 tensor([104, 129,  63, 130, 113,  79, 117, 113,  27,  53,  61,  86,  26, 109,
         98,  36, 106, 128,  74,  43, 126, 129,  71,  84])

Road 2 data:
 tensor([164,  21,  29, 129,  29,  40, 141, 112,  83, 100,  95, 185, 122,  39,
        131, 188, 138,  63, 216,  49,  51, 137,  63,  35])

Total hourly vehicle flow across both roads:
 tensor([268, 150,  92, 259, 142, 119, 258, 225, 110, 153, 156, 271, 148, 148,
        229, 224, 244, 191, 290,  92, 177, 266, 134, 119])

Total vehicles on Road 1 in a day: 2105
Total vehicles on Road 2 in a day: 2360
Overall total vehicle flow (both roads combined): 4465


In [7]:
#3 Write the function to calculate the total vehicle flow for each hour across both roads

total_vehicle_flow_for_each_hour = R1+R2

total_vehicle_flow_for_each_hour



tensor([268, 150,  92, 259, 142, 119, 258, 225, 110, 153, 156, 271, 148, 148,
        229, 224, 244, 191, 290,  92, 177, 266, 134, 119])



---



**Task3: Fitness Matrix**

The AI Gym tracks members’ fitness scores using a 3×3 matrix for *strength*, *stamina*, and f*lexibility*. Each row represents a different member, and each column represents a specific metric.

In [8]:
#1 Create a 3*3 tensor matrix and multiply the scores of each member by a weight factor: [0.8, 1.2, 1.5]

gym_score = [[10,20,30],
             [20,30,40],
             [30,40,50]]
gym_score_T = torch.tensor(gym_score, dtype=torch.float32)

gym_score_T

w_f = [0.8, 1.2, 1.5]

w_f_T = torch.tensor(w_f, dtype=torch.float32)



score_mf = w_f_T * gym_score_T

score_mf


tensor([[ 8., 24., 45.],
        [16., 36., 60.],
        [24., 48., 75.]])

In [9]:
#2 Find the row-wise and column-wise maximum scores

print(score_mf.max(dim=1))

print(score_mf.max(dim=0))



torch.return_types.max(
values=tensor([45., 60., 75.]),
indices=tensor([2, 2, 2]))
torch.return_types.max(
values=tensor([24., 48., 75.]),
indices=tensor([2, 2, 2]))


In [10]:
#3 Transpose the fitness matrix and interpret it's new structure (shape)


score_mf.T

tensor([[ 8., 16., 24.],
        [24., 36., 48.],
        [45., 60., 75.]])



---



**Task4: Chain Rule in Action**

AI Lab is running experiments to understand the effect of temperature (
x) on a chemical reaction rate (y). The relationship is given as:
$y = 2x^3 + 5x^2 - 3x + 7$



In [11]:
#1 Use PyTorch to compute 'y' for x = 4

x = torch.tensor(4)

y = 2 * x ** 3 + 5*x**2-3*x+7

y


tensor(203)

In [12]:
#2 Calculate dy/dx(gradient) using PyTorch's autograd


x = torch.tensor(4.0, requires_grad=True)
y = 6 * x**2 + 10*x
y.backward()

x.grad

tensor(58.)



---



**Task5: Camera Calibration**

AI Town’s surveillance cameras need to align their focus. You are given the following matrices for two cameras’ focus adjustments:

In [13]:

camera1 = torch.tensor([[1, 2], [3, 4]])
camera2 = torch.tensor([[5, 6], [7, 8]])


In [14]:
#1 Perform an element-wise multiplication of matrices ( Hadamard Product)


product = camera1 * camera2

product

tensor([[ 5, 12],
        [21, 32]])

In [15]:
camera1.flatten()

tensor([1, 2, 3, 4])

In [16]:
#2 Compute Dot Product of the two matrices


dot_product = torch.dot(camera1.flatten(),camera2.flatten())

dot_product


tensor(70)

In [17]:
#3 Compute the Determinant of each matrix

camera1_1 = torch.tensor(camera1, dtype=torch.float32)

camera2_1 = torch.tensor(camera2, dtype=torch.float32)



det_cam1 = torch.det(camera1_1)
det_cam2 = torch.det(camera2_1)

print(det_cam1,det_cam2)

tensor(-2.) tensor(-2.0000)


/tmp/ipython-input-3429461421.py:3: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  camera1_1 = torch.tensor(camera1, dtype=torch.float32)
/tmp/ipython-input-3429461421.py:5: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  camera2_1 = torch.tensor(camera2, dtype=torch.float32)




---



**Task6: Neural Network Foundations**

Our AI University uses simplified single neuron model (perceptron):
$$y = wx + b$$

In [22]:
#1 Create tensors for w  = 2, b = 1, x = [1, 2, 3, 4]


w = torch.tensor([2])

b = torch.tensor([1])

x = torch.tensor([1,2,3,4])


print(w,b,x)

tensor([2]) tensor([1]) tensor([1, 2, 3, 4])


In [24]:
#2 Compute tensors for y



y = w*x + b
y

tensor([3, 5, 7, 9])



---

